export const jwtToken =
  'Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJreXVyaTk5QG5hdmVyLmNvbSIsImF1dGgiOiJST0xFX1VTRVIsUk9MRV9VU0VSIiwiaXNBZGRpdGlvbmFsSW5mb1Byb3ZpZGVkIjp0cnVlLCJleHAiOjE2OTgyMTM5Mzd9.dp8THdFQy6nkhv9jOh9deBCdDCP3KPFIXQZfp8RFdrDlfOmyuXMnnm0iCMrKcoZxC2Buz6IvmCXuMx6NDSFjjQ';
export const chatServer = 'https://chat.kiwes.org';
